IF OBJECT_ID(N'Basketball.Team') IS NULL
BEGIN
   CREATE TABLE Basketball.Team
    (
	    TeamId INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	    ConferenceId INT NOT NULL FOREIGN KEY
		    REFERENCES Basketball.Conference(ConferenceId),
	    Name NVARCHAR(50) NOT NULL UNIQUE,
	    Mascot NVARCHAR(50) NOT NULL,
	    City NVARCHAR(30) NOT NULL,
	    State NVARCHAR(15) NOT NULL,
	    CreatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
        UpdatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET())
    );
END;
