IF OBJECT_ID(N'Basketball.Player') IS NULL
CREATE TABLE Basketball.Player
(
	PlayerId INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	TeamId INT NOT NULL UNIQUE FOREIGN KEY
		REFERENCES Basketball.Team(TeamId),
	FirstName NVARCHAR(20) NOT NULL,
	LastName NVARCHAR(20) NOT NULL,
	Position NVARCHAR(2) NOT NULL,
	CreatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
    UpdatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
);

