IF OBJECT_ID(N'Basketball.Game') IS NULL
CREATE TABLE Basketball.Game
(
	GameId INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	SeasonId INT NOT NULL FOREIGN KEY
		REFERENCES Basketball.Season(SeasonId),
	Neutral BIT NOT NULL,
	Date DATE NOT NULL,
	CreatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
    UpdatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
);
